# Example

agents: 100             # Number of agents in the simulation
world_size: 500         # The size of the simulated environment
sim_duration: 1000      # Duration of the simulation in time steps
logging_level: INFO     # Log level (DEBUG, INFO, WARNING, ERROR)
output_file: "output/results.csv"  # File path for saving simulation results